# Generated by Django 5.2.4 on 2025-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_unique_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marketing_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
