# Generated by Django 5.2.4 on 2025-10-01 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128)),
                ('locale', models.CharField(default='fr', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ['slug', 'locale', '-version'],
                'indexes': [models.Index(fields=['slug', 'locale'], name='template_slug_locale_idx'), models.Index(fields=['is_active'], name='template_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'locale', 'version'), name='uniq_email_template_version')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=64)),
                ('dedup_key', models.CharField(max_length=128)),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('locale', models.CharField(default='fr', max_length=12)),
                ('template_slug', models.CharField(max_length=128)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('subject_override', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='queued', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=512)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbox email',
                'verbose_name_plural': 'Outbox emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='outbox_status_schedule_idx'), models.Index(fields=['namespace', 'status'], name='outbox_namespace_status_idx'), models.Index(fields=['locked_at'], name='outbox_locked_idx')],
                'constraints': [models.UniqueConstraint(fields=('namespace', 'dedup_key'), name='uniq_outbox_namespace_dedup_key')],
            },
        ),
        migrations.CreateModel(
            name='EmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry')], max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='messaging.outboxemail')),
            ],
            options={
                'verbose_name': 'Email attempt',
                'verbose_name_plural': 'Email attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outbox_id', 'created_at'], name='attempt_outbox_created_idx')],
            },
        ),
    ]
