# Generated by Django 5.2.4 on 2025-10-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxemail',
            name='rendered_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outboxemail',
            name='rendered_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outboxemail',
            name='rendered_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
