# Generated by Django 5.2.4 on 2025-10-01 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_seed_initial_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('template_slug', models.CharField(max_length=128)),
                ('locale', models.CharField(default='fr', max_length=12)),
                ('subject_override', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=16)),
                ('batch_size', models.PositiveIntegerField(default=500)),
                ('dry_run', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='campaign_status_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('locale', models.CharField(default='fr', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('suppressed', 'Suppressed')], default='pending', max_length=16)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_recipient_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'email'), name='uniq_campaign_email')],
            },
        ),
    ]
