# Generated by Django 5.2.4 on 2025-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_campaign_campaignrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxemail',
            name='flow_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='outboxemail',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboxemail',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='queued', max_length=16),
        ),
    ]
