# Generated by Django 5.2.4 on 2025-10-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=160)),
                ('object_id', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='active', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('import', 'Import'), ('seed', 'Seed')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'string translation',
                'verbose_name_plural': 'string translations',
                'indexes': [models.Index(fields=['model_label', 'object_id', 'field', 'language'], name='i18n_string_mo_ba0509_idx')],
                'unique_together': {('model_label', 'object_id', 'field', 'language')},
            },
        ),
    ]
