# Generated by Django 5.2.4 on 2025-09-26 08:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0004_coursesidebarsettings_coursetrainingcontent_and_more'),
        ('marketing', '0003_alter_pricebonusitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_pct_effective',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='list_price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='price_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketing.priceplan'),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.course'),
        ),
    ]
