# Generated by Django 5.2.4 on 2025-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
