# Generated by Django 5.2.4 on 2025-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lecture_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
