# Generated by Django 5.2.4 on 2025-09-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lecture_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureVideoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fr_FR', 'Français (France)'), ('ar_MA', 'Arabe (Maroc)')], max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_variants', to='content.lecture')),
            ],
            options={
                'ordering': ('lecture', 'lang'),
                'constraints': [models.UniqueConstraint(fields=('lecture', 'lang'), name='unique_lecture_lang_variant')],
            },
        ),
    ]
