# Generated by Django 5.2.4 on 2025-10-13 19:51

import django.db.models.deletion
import parler.models
from django.conf import settings
from django.db import migrations, models


def forwards_copy_content_translations(apps, schema_editor):
    default_language = getattr(settings, 'PARLER_DEFAULT_LANGUAGE_CODE', 'fr') or 'fr'

    Section = apps.get_model('content', 'Section')
    SectionTranslation = apps.get_model('content', 'SectionTranslation')
    for section in Section.objects.all().iterator():
        SectionTranslation.objects.create(
            master_id=section.pk,
            language_code=default_language,
            title=section.title or "",
        )

    Lecture = apps.get_model('content', 'Lecture')
    LectureTranslation = apps.get_model('content', 'LectureTranslation')
    for lecture in Lecture.objects.all().iterator():
        LectureTranslation.objects.create(
            master_id=lecture.pk,
            language_code=default_language,
            title=lecture.title or "",
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_seed_multilang_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.lecture')),
            ],
            options={
                'verbose_name': 'lecture Translation',
                'db_table': 'content_lecture_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.section')),
            ],
            options={
                'verbose_name': 'section Translation',
                'db_table': 'content_section_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(forwards_copy_content_translations, backwards_noop),
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
    ]
