# Generated by Django 5.2.4 on 2025-10-15 09:02

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations
from django.db.migrations.operations.base import Operation


class _AlterModelBases(Operation):
    reduces_to_sql = False
    reversible = False

    def __init__(self, model_name: str, bases: tuple):
        self.model_name = model_name
        self.bases = bases

    def state_forwards(self, app_label, state):
        model_state = state.models[(app_label, self.model_name.lower())]
        model_state.bases = self.bases

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        raise NotImplementedError("This schema change is not automatically reversible.")

    def describe(self):
        return f"Set base classes for {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_lecture_title_remove_section_title_and_more'),
    ]

    operations = [
        _AlterModelBases('Lecture', (parler.models.TranslatableModel,)),
        _AlterModelBases('Section', (parler.models.TranslatableModel,)),
        migrations.AlterField(
            model_name='lecturetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.lecture'),
        ),
        migrations.AlterField(
            model_name='sectiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.section'),
        ),
    ]
