# Generated by Django 5.2.4 on 2025-09-27 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lead', 'Lead'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=32)),
                ('action_key', models.CharField(max_length=64)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gclid', models.CharField(blank=True, max_length=255, null=True)),
                ('gbraid', models.CharField(blank=True, max_length=255, null=True)),
                ('wbraid', models.CharField(blank=True, max_length=255, null=True)),
                ('gclsrc', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=16)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enhanced_identifiers', models.JSONField(blank=True, default=dict)),
                ('adjustment_type', models.CharField(blank=True, max_length=32, null=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ERROR', 'Error'), ('SKIPPED_NO_CONSENT', 'Skipped (no consent)')], default='PENDING', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('google_upload_status', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Ads conversion record',
                'verbose_name_plural': 'Google Ads conversion records',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='adsbridge_status_idx'), models.Index(fields=['order_id'], name='adsbridge_order_idx'), models.Index(fields=['action_key'], name='adsbridge_action_idx')],
            },
        ),
    ]
