# Generated by Django 5.2.4 on 2025-09-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsbridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrecord',
            name='effective_mode',
            field=models.CharField(default='on', max_length=16),
        ),
        migrations.AddField(
            model_name='conversionrecord',
            name='hold_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HELD', 'Held'), ('SENT', 'Sent'), ('ERROR', 'Error'), ('SKIPPED_NO_CONSENT', 'Skipped (no consent)')], default='PENDING', max_length=32),
        ),
    ]
