# Generated by Django 5.2.4 on 2025-09-11 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_kind', models.CharField(choices=[('email_ebook', 'Email contre ebook'), ('contact_full', 'Formulaire contact complet'), ('checkout_intent', "Intention d'achat (Stripe)")], max_length=32)),
                ('campaign', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('course_slug', models.SlugField(blank=True, default='', max_length=220)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=64)),
                ('billing_address_line1', models.CharField(blank=True, default='', max_length=200)),
                ('billing_address_line2', models.CharField(blank=True, default='', max_length=200)),
                ('billing_city', models.CharField(blank=True, default='', max_length=100)),
                ('billing_state', models.CharField(blank=True, default='', max_length=100)),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('billing_country', models.CharField(blank=True, default='', max_length=2)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('tax_id_type', models.CharField(blank=True, default='', max_length=16)),
                ('tax_id', models.CharField(blank=True, default='', max_length=32)),
                ('save_customer', models.BooleanField(default=False)),
                ('accept_terms', models.BooleanField(default=False)),
                ('invoice_language', models.CharField(blank=True, default='', max_length=8)),
                ('ebook_id', models.CharField(blank=True, default='', max_length=64)),
                ('newsletter_optin', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('signed_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('honeypot_value', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Validé'), ('REJECTED', 'Rejeté'), ('FAILED_TEMP', 'Echec temporaire')], default='PENDING', max_length=16)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('risk_flags', models.JSONField(blank=True, default=dict)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('referer', models.CharField(blank=True, default='', max_length=500)),
                ('page_path', models.CharField(blank=True, default='', max_length=300)),
                ('locale', models.CharField(blank=True, default='', max_length=16)),
                ('ab_variant', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='billing.order')),
            ],
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['form_kind', 'email', 'created_at'], name='leads_lead_form_ki_374ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['course_slug', 'created_at'], name='leads_lead_course__814bf1_idx'),
        ),
    ]
