# Generated by Django 5.2.4 on 2025-09-16 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(max_length=64)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Validé'), ('REJECTED', 'Rejeté'), ('FAILED_TEMP', 'Echec temporaire')], default='PENDING', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['lead', 'flow_key', 'created_at'], name='leads_leads_lead_id_0602ae_idx'), models.Index(fields=['status'], name='leads_leads_status_832877_idx')],
                'unique_together': {('lead', 'flow_key', 'session_key')},
            },
        ),
    ]
