# Generated by Django 5.2.4 on 2025-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadsubmissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='form_kind',
            field=models.CharField(choices=[('email_ebook', 'Email contre ebook'), ('contact_full', 'Formulaire contact complet'), ('checkout_intent', "Intention d'achat (Stripe)"), ('product_lead', 'Lead produit')], max_length=32),
        ),
    ]
