# Generated by Codex CLI on 2025-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_form_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsubmissionlog',
            name='step',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='leadsubmissionlog',
            index=models.Index(fields=['flow_key', 'session_key', 'step'], name='leadsubm_step_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsubmissionlog',
            unique_together={('lead', 'flow_key', 'session_key', 'step')},
        ),
    ]
