# Generated by Django 5.2.4 on 2025-10-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadsubmissionlog_step'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadsubmissionlog',
            new_name='leads_leads_flow_ke_04cea5_idx',
            old_name='leadsubm_step_idx',
        ),
    ]
