# Generated by Django 5.2.4 on 2025-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_leadsubm_step_idx_leads_leads_flow_ke_04cea5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pack_slug',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
