pages:
  online_home:
    meta:
      title: "Lumière Academy — Fabrication de bougies"
      description: "Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      modals_login:
        component: "core/modals/login"
      hero:
        component: "hero/cover"
        cache: true
      learning_card:
        component: "learning/card"
      learning_content:
        component: "learning/content"
      highlights:
        component: "learning/highlights"
      faq:
        component: "faq/main"
      trainer:
        component: "trainer/profile"
      footer:
        component: "footer/main"
      lead_form:
        component: "forms/shell"
      chatbot:
        component: "chatbot/shell"
        cache: false
  test:
    meta:
      title: "(Test) Lumière Academy — Fabrication de bougies"
      description: "(Test) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      contact_info:
        component: "contact/info"
        params:
          phone_tel: "+212 600 000 000"
          phone_display: "+212 600 000 000"
          phone_title: "Numéro de téléphone"
          email: "atelier@example.com"
          email_title: "Adresse email"
          address_url: "https://example.com/campus"
          address_text: "123 Rue Exemple, Rabat"
          address_title: "Adresse du bureau"
      contact_map:
        component: "contact/map"
        params:
          map_embed_url: "https://maps.example.com/embed/demo"
      chatbot:
        component: "chatbot/shell"
        cache: false
  course_detail:
    meta:
      title: "(Cours) Lumière Academy — Fabrication de bougies"
      description: "(Cours) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      modals_login:
        component: "core/modals/login"
      training_block:
        component: "course_detail/training"
      sidebar_block:
        component: "course_detail/sidebar"
      chatbot:
        component: "chatbot/shell"
        cache: false
  course_list:
    component: "courses/list"
    params:
      limit: 6
      list_title: "Nos formations populaires"
      list_subtitle: "Sélectionnez un cours pour démarrer votre parcours."
      label_languages: "Langues : 🇲🇦 / 🇫🇷"
      label_lessons: "+30 cours"
      label_score: "Score"
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      modals_login:
        component: "core/modals/login"
      chatbot:
        component: "chatbot/shell"
        cache: false
  lecture:
    template: screens/lecture.html
    params:
      assets:
        images:
          poster: "/static/images/formateurs/cover-video-landing.jpg"
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      modals_login:
        component: "core/modals/login"
      main:
        component: core/learning/lecture
      chatbot:
        component: "chatbot/shell"
        cache: false
  courses:
    meta:
      title: "(Test) Lumière Academy — Fabrication de bougies"
      description: "(Test) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      modals_login:
        component: "core/modals/login"
      course_list:
        component: "courses/list"
      faq:
        component: "faq/main"
      fab_whatsapp:
        component: "fab/whatsapp"
        params:
          label: "Besoin d’aide ?"
          icon_mode: "vendor"
          icon_vendor: "icofont-whatsapp"
          offset_bottom: 18
          offset_right: 16
          phone_tel: "+212719646705"
          prefill_text: "Bonjour, j’ai une question sur le pack Alfenna."
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  product_detail:
    meta:
      title: "Produit"
      description: "Fiche detaillee d'un produit Lumière."
    slots:
      vendors:
        component: "vendors/core"
      header:
        component: "header/modes"
      product_hero:
        component: "core/product"
        params:
          lookup:
            slug: "{{ url.kwargs.product_slug }}"
          product:
            id: "demo-product"
            name: "Sajadat Al-Raha"
            description: "Tapis de priere a memoire de forme pour un confort maximal."
            price: 399
            promo_price: 329
            currency: "MAD"
            badges:
              - { icon: "fas fa-truck", text: "Livraison 48h" }
              - { icon: "fas fa-money-bill", text: "Paiement a la livraison" }
            highlights:
              - "Soulage genoux et dos"
              - "Mousse memo haute densite"
              - "Housse antiderapante"
#          media:
#            lightbox: true
#            images:
#              - { src: "/static/carpet/images/cover/cadre-domestique.webp", alt: "Vue principale" }
#              - { src: "/static/carpet/images/cover/genous-coussin.webp", alt: "Zoom coussin" }
          form:
            alias: "core/forms/lead_step3"
            action_url: "leads:collect"
            fields_map:
              fullname: "full_name"
              phone: "phone_number"
              address: "address"
              quantity: "quantity"
              offer: "offer_key"
              product: "product"
              promotion: "promotion_selected"
          tracking:
            enabled: true
            events:
              view: "lp_variant_view"
              media_switch: "product_media_switch"
      sticky_buybar_v2:
        component: "sticky/buybar_v2"
      faq:
        component: "faq/main"
      fab_whatsapp:
        component: "fab/whatsapp"
        params:
          label: "Besoin d’aide ?"
          icon_mode: "vendor"
          icon_vendor: "icofont-whatsapp"
          offset_bottom: 18
          offset_right: 16
          phone_tel: "+212719646705"
          prefill_text: "Bonjour, j’ai une question sur le pack Alfenna."
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  faq:
    meta:
      title: "Lumière Academy — Questions fréquentes"
      description: "Réponses aux questions fréquentes sur les formations Lumière Academy."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      faq:
        component: "faq/main"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  register:
    template: screens/register.html
    meta:
      title: "Créer un compte — Lumière Academy"
      description: "Inscrivez-vous pour accéder aux cours et contenus exclusifs."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false
      main:
        component: "accounts/register/shell"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  check_email:
    template: screens/auth_message.html
    meta:
      title: "Vérifie ta boîte mail — Lumière Academy"
      description: "Nous t'avons envoyé un e-mail pour confirmer ton inscription."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/check_email"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  password_reset:
    template: screens/password_reset.html
    meta:
      title: "Mot de passe oublié — Lumière Academy"
      description: "Recevez un lien sécurisé pour réinitialiser votre mot de passe."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false
      main:
        component: "accounts/password_reset/shell"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  password_reset_done:
    template: screens/auth_message.html
    meta:
      title: "E-mail envoyé — Lumière Academy"
      description: "Vérifie ta boîte mail pour réinitialiser ton mot de passe."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/done"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  password_reset_confirm:
    template: screens/auth_message.html
    meta:
      title: "Définir un nouveau mot de passe — Lumière Academy"
      description: "Choisissez un nouveau mot de passe sécurisé pour votre compte."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/confirm"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  password_reset_complete:
    template: screens/auth_message.html
    meta:
      title: "Mot de passe mis à jour — Lumière Academy"
      description: "Votre mot de passe a été modifié avec succès."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/complete"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  verification_success:
    template: screens/auth_message.html
    meta:
      title: "Adresse confirmée — Lumière Academy"
      description: "Ton adresse e-mail est maintenant vérifiée."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/verify_success"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  verification_error:
    template: screens/auth_message.html
    meta:
      title: "Lien invalide — Lumière Academy"
      description: "Ce lien de validation n'est plus actif. Demande un nouvel e-mail."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/verify_error"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
