pages:
  online_home:
    meta:
      title: "Lumière Academy — Fabrication de bougies"
      description: "Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      hero:
        component: "hero/cover"
        cache: true
      learning_card:
        component: "learning/card"
      learning_content:
        component: "learning/content"
      highlights:
        component: "learning/highlights"
      contact_info:
        component: "fr/contact/phone"
      faq:
        component: "faq/main"
      trainer:
        component: "trainer/profile"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  test:
    meta:
      title: "(Test) Lumière Academy — Fabrication de bougies"
      description: "(Test) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      contact_info:
        component: "fr/contact/phone"
      contact_map:
        component: "contact/map"
        params:
          map_embed_url: "https://maps.example.com/embed/demo"
      course_list:
        component: "courses/list"
        params:
          limit: 6
          list_title: "Nos formations populaires"
          list_subtitle: "Sélectionnez un cours pour démarrer votre parcours."
          label_languages: "Langues : 🇲🇦 / 🇫🇷"
          label_lessons: "+30 cours"
          label_score: "Score"
      training_block:
        component: "course_detail/training"
        params:
          hero_tag: "Artisanat & Créativité"
          video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          video_label: "Lire la présentation"
          title: "Formation complète en fabrication de bougies"
          subtitle: "Découverte, techniques avancées et lancement d'activité."
          enrollment_label: "+500 apprenants satisfaits"
          rating_value: 4.8
          rating_count: 1250
          description_title: "Description"
          description_blocks:
            - "Découvrez comment créer des bougies uniques pas à pas."
            - "Approfondissez votre savoir-faire avec des modules vidéo détaillés."
          bundle_title: "Bundle exclusif"
          bundle_items:
            - "Accès illimité à la bibliothèque vidéo"
            - "Guide PDF téléchargeable"
            - "Support communauté pendant 30 jours"
          curriculum_title: "Programme"
          curriculum_sections:
            - title: "Module 1 — Bases"
              items:
                - "Choisir les matériaux essentiels"
                - "Préparer son atelier"
            - title: "Module 2 — Techniques"
              items:
                - "Techniques de coulée"
                - "Finitions et parfums"
          instructors_title: "Formateurs"
          instructors:
            - name: "Souheila Jebbari"
              role: "Formatrice principale"
              bio: "Spécialiste des bougies naturelles."
            - name: "Naila Baiga"
              role: "Experte design"
              bio: "Accompagne les apprenants sur les finitions décoratives."
          reviews_title: "Avis"
          reviews:
            - author: "Salma"
              location: "Artisane, Tanger"
              content: "Une formation inspirante avec un excellent suivi."
            - author: "Mehdi"
              location: "Entrepreneur, Fès"
              content: "Parcours structuré et concret pour lancer son activité."
          reviews_cta_label: "Voir tous les avis"
          reviews_cta_url: "https://lumiereacademy.com/temoignages"
      sidebar_block:
        component: "course_detail/sidebar"
        params:
          course_slug: "demo-course"
          currency: "MAD"
          promo_badge: "Promo spéciale"
          info_items:
            - icon: "icofont-man-in-glasses"
              label: "Formatrice"
              value: "Souheila Jebbari"
            - icon: "icofont-clock-time"
              label: "Durée"
              value: "06h00"
            - icon: "icofont-ui-video-play"
              label: "Vidéos"
              value: "30 modules"
            - icon: "icofont-book-alt"
              label: "Langue"
              value: "🇲🇦 / 🇫🇷"
          bundle_title: "Bonus inclus"
          bundle_items:
            - "Accès communauté privée"
            - "Réductions sur les ateliers présentiels"
          cta_guest_label: "Acheter sans inscription"
          cta_member_label: "Se connecter pour continuer"
          cta_note: "Achat possible en mode invité"
      chatbot:
        component: "chatbot/shell"
        cache: false
  product_detail:
    meta:
      title: "Produit"
      description: "Fiche detaillee d'un produit Lumière."
    slots:
      vendors:
        component: "vendors/core"
      header:
        component: "header/modes"
      product_hero:
        component: "core/product"
        params:
          lookup:
            slug: "{{ url.kwargs.product_slug }}"
          product:
            id: "demo-product"
            name: "Sajadat Al-Raha"
            description: "Tapis de priere a memoire de forme pour un confort maximal."
            price: 399
            promo_price: 329
            currency: "MAD"
            badges:
              - { icon: "fas fa-truck", text: "Livraison 48h" }
              - { icon: "fas fa-money-bill", text: "Paiement a la livraison" }
            highlights:
              - "Soulage genoux et dos"
              - "Mousse memo haute densite"
              - "Housse antiderapante"
#          media:
#            lightbox: true
#            images:
#              - { src: "/static/carpet/images/cover/cadre-domestique.webp", alt: "Vue principale" }
#              - { src: "/static/carpet/images/cover/genous-coussin.webp", alt: "Zoom coussin" }
          form:
            alias: "core/forms/lead_step3"
            action_url: "leads:collect"
            fields_map:
              fullname: "full_name"
              phone: "phone_number"
              address: "address"
              quantity: "quantity"
              offer: "offer_key"
              product: "product"
              promotion: "promotion_selected"
          tracking:
            enabled: true
            events:
              view: "lp_variant_view"
              media_switch: "product_media_switch"
      sticky_buybar_v2:
        component: "sticky/buybar_v2"
      faq:
        component: "faq/main"
      fab_whatsapp:
        component: "fab/whatsapp"
        params:
          label: "Besoin d’aide ?"
          icon_mode: "vendor"
          icon_vendor: "icofont-whatsapp"
          offset_bottom: 18
          offset_right: 16
          phone_tel: "+212719646705"
          prefill_text: "Bonjour, j’ai une question sur le pack Alfenna."
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  contact:
    meta:
      title: "(Test) Lumière Academy — Fabrication de bougies"
      description: "(Test) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      contact_info:
        component: "fr/contact/phone"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  register:
    path: "/inscription/"
    template: screens/register.html
    meta:
      title: "Inscription — Lumière Academy"
      description: "Créer un compte pour accéder aux cours."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false
      main:
        component: "accounts/register/shell"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  password_reset:
    path: "/mot-de-passe-oublie/"
    template: screens/password_reset.html
    meta:
      title: "Mot de passe oublié — Lumière Academy"
      description: "Recevez un lien de réinitialisation."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false
      main:
        component: "accounts/password_reset/shell"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  check_email:
    path: "/inscription/check-email/"
    template: screens/auth_message.html
    meta:
      title: "Vérifie ta boîte mail — Lumière Academy"
      description: "Confirme ton adresse pour activer ton compte."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/check_email"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  verification_success:
    path: "/verification/succes/"
    template: screens/auth_message.html
    meta:
      title: "E-mail vérifié — Lumière Academy"
      description: "Ton adresse e-mail est confirmée."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/verify_success"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  verification_error:
    path: "/verification/erreur/"
    template: screens/auth_message.html
    meta:
      title: "Lien expiré — Lumière Academy"
      description: "Demande un nouvel e-mail de confirmation."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/verify_error"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  password_reset_done:
    path: "/mot-de-passe-oublie/envoye/"
    template: screens/auth_message.html
    meta:
      title: "E-mail envoyé — Lumière Academy"
      description: "Vérifie ta boîte mail pour réinitialiser ton mot de passe."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/done"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  password_reset_confirm:
    path: "/mot-de-passe-oublie/definir/{uidb64}/{token}/"
    template: screens/auth_message.html
    meta:
      title: "Définir un nouveau mot de passe — Lumière Academy"
      description: "Choisis un mot de passe sécurisé."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/confirm"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  password_reset_complete:
    path: "/mot-de-passe-oublie/termine/"
    template: screens/auth_message.html
    meta:
      title: "Mot de passe mis à jour — Lumière Academy"
      description: "Tu peux te connecter avec ton nouveau mot de passe."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      main:
        component: "accounts/password_reset/complete"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false

  courses:
    meta:
      title: "(Test) Lumière Academy — Fabrication de bougies"
      description: "(Test) Participez à nos cours et apprenez des techniques artisanales."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false   # header dynamique => jamais cacheté
      course_list:
        component: "courses/list"
      faq:
        component: "faq/main"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  faq:
    meta:
      title: "Lumière Academy — Questions fréquentes"
      description: "Retrouvez les réponses aux questions fréquentes sur nos formations."
    slots:
      vendors:
        component: "vendors/core"
      header:
        experiment: header_ab
        variants:
          A: "header/struct"
          B: "header/modes"
        cache: false
      faq:
        component: "faq/main"
      footer:
        component: "footer/main"
      chatbot:
        component: "chatbot/shell"
        cache: false
  lecture:
    template: screens/lecture.html
    params:
      assets:
        images:
          poster: "/static/images/formateurs/cover-video-landing.jpg"
    slots:
      main:
        component: core/learning/lecture
      chatbot:
        component: "chatbot/shell"
        cache: false

  'billing/success':
    template: screens/fr/billing/success.html
    meta:
      title: "Paiement confirmé — Lumière Academy"
      description: "Merci pour votre achat. Votre accès arrive dans quelques minutes."
    slots:
      vendors:
        component: "vendors/core"
        cache_key: "vendors|v:fr"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      message:
        component: "checkout/thank_you_message"
        cache_key: "billing_success_message|v:fr"
        params:
          title: "Paiement confirmé — merci 🙌"
      footer:
        component: "footer/main"
        cache_key: "footer_main|v:fr"
      chatbot:
        component: "chatbot/shell"
        cache: false
  'billing/cancel':
    template: screens/fr/billing/cancel.html
    meta:
      title: "Paiement annulé — Lumière Academy"
      description: "Le paiement a été interrompu. Vous pouvez relancer le processus ou contacter notre équipe."
    slots:
      vendors:
        component: "vendors/core"
        cache_key: "vendors|v:fr"
      header:
        experiment: header_ab
        variants:
          A: "header/modes"
          B: "header/struct"
        cache: false
      message:
        component: "checkout/thank_you_message"
        cache_key: "billing_cancel_message|v:fr"
        params:
          title: "Paiement interrompu"
          paragraphs:
            - "Votre paiement a été annulé ou n'a pas abouti."
            - "Vous pouvez reprendre le processus quand vous le souhaitez."
          info_box:
            title: "Besoin d'aide ?"
            paragraphs:
              - "Contactez notre équipe support pour finaliser votre inscription."
      footer:
        component: "footer/main"
        cache_key: "footer_main|v:fr"
      chatbot:
        component: "chatbot/shell"
        cache: false
