# Generated by Django 5.2.4 on 2025-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=120)),
                ('base_url', models.URLField(blank=True, default='')),
                ('default_locale', models.CharField(blank=True, default='fr_FR', max_length=12)),
                ('default_image', models.URLField(blank=True, default='')),
                ('twitter_site', models.CharField(blank=True, default='', max_length=60)),
                ('twitter_creator', models.CharField(blank=True, default='', max_length=60)),
                ('facebook_app_id', models.CharField(blank=True, default='', max_length=50)),
                ('gtm_id', models.CharField(blank=True, default='', max_length=32, verbose_name='GTM Container ID')),
                ('ga4_id', models.CharField(blank=True, default='', max_length=32, verbose_name='GA4 Measurement ID')),
                ('meta_pixel_id', models.CharField(blank=True, default='', max_length=32)),
                ('tiktok_pixel_id', models.CharField(blank=True, default='', max_length=32)),
                ('consent_cookie_name', models.CharField(blank=True, default='cookie_consent_marketing', max_length=64)),
                ('robots_default', models.CharField(blank=True, default='index,follow', help_text='Valeur par défaut pour les pages publiques', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Marketing globaux',
            },
        ),
    ]
