# Generated by Django 5.2.4 on 2025-09-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('currency_symbol', models.CharField(default='€', max_length=8)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('old_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('ribbon_label', models.CharField(blank=True, default='', max_length=60)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('cta_url', models.URLField(blank=True, default='')),
                ('cta_sublabel', models.CharField(blank=True, default='', max_length=140)),
                ('cta_aria', models.CharField(blank=True, default='', max_length=140)),
                ('second_cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('second_cta_url', models.URLField(blank=True, default='')),
                ('second_cta_aria', models.CharField(blank=True, default='', max_length=140)),
                ('payment_note', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('included', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.priceplan')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBonusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.priceplan')),
            ],
        ),
    ]
