# Generated by Django 5.2.4 on 2025-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_priceplan_pricefeature_pricebonusitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricebonusitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pricefeature',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='priceplan',
            options={'ordering': ['display_order', 'id']},
        ),
    ]
