# Generated by Django 5.2.4 on 2025-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_pricebonusitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceplan',
            options={'ordering': ['priority', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='priceplan',
            name='currency',
            field=models.CharField(default='€', max_length=8),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='value_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
