# Generated by Django 5.2.4 on 2025-09-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_priceplan_options_priceplan_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('icon_class', models.CharField(blank=True, default='', help_text='Classe CSS d’icône (Font Awesome / Icofont / Flaticon).', max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonusfeature_set', to='marketing.priceplan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
