# Generated by Django 5.2.4 on 2025-09-16 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.SlugField(max_length=64)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('current_step', models.CharField(blank=True, default='', max_length=64)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=16)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('scheduled_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_touch_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_sessions', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['flow_key', 'session_key'], name='flowforms_f_flow_ke_8ed8af_idx'), models.Index(fields=['status'], name='flowforms_f_status_0438cd_idx'), models.Index(fields=['last_touch_at'], name='flowforms_f_last_to_1e9403_idx')],
                'unique_together': {('flow_key', 'session_key')},
            },
        ),
    ]
