# Generated by Django 5.2.4 on 2025-09-27 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEventRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_uuid', models.UUIDField(unique=True)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('site_version', models.CharField(blank=True, db_index=True, max_length=32)),
                ('page_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('slot_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('component_alias', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('scroll', 'Scroll depth'), ('heatmap', 'Heatmap click')], max_length=16)),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('consent', models.CharField(max_length=1)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('device', models.CharField(blank=True, db_index=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('referer', models.CharField(blank=True, max_length=512)),
                ('ua_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Raw Event',
                'verbose_name_plural': 'Analytics Raw Events',
                'db_table': 'atelier_analytics_event_raw',
                'indexes': [models.Index(fields=['page_id', 'slot_id', 'event_type', 'ts'], name='aa_raw_page_slot_evt'), models.Index(fields=['component_alias', 'event_type', 'ts'], name='aa_raw_alias_evt')],
            },
        ),
        migrations.CreateModel(
            name='ComponentStatDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('site_version', models.CharField(blank=True, max_length=32)),
                ('page_id', models.CharField(blank=True, max_length=128)),
                ('slot_id', models.CharField(blank=True, max_length=128)),
                ('component_alias', models.CharField(blank=True, max_length=128)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('avg_scroll_pct', models.FloatField(default=0.0)),
                ('uu_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Daily Stat',
                'verbose_name_plural': 'Component Daily Stats',
                'db_table': 'atelier_component_stat_daily',
                'indexes': [models.Index(fields=['date', 'page_id', 'slot_id'], name='aa_cmp_daily_lookup')],
                'unique_together': {('date', 'site_version', 'page_id', 'slot_id', 'component_alias')},
            },
        ),
        migrations.CreateModel(
            name='HeatmapBucketDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('site_version', models.CharField(blank=True, max_length=32)),
                ('page_id', models.CharField(blank=True, max_length=128)),
                ('device', models.CharField(blank=True, max_length=8)),
                ('bucket_x', models.PositiveSmallIntegerField()),
                ('bucket_y', models.PositiveSmallIntegerField()),
                ('hits', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heatmap Bucket Daily',
                'verbose_name_plural': 'Heatmap Bucket Daily',
                'db_table': 'atelier_heatmap_bucket_daily',
                'indexes': [models.Index(fields=['date', 'page_id', 'device'], name='aa_heatmap_lookup')],
                'unique_together': {('date', 'site_version', 'page_id', 'device', 'bucket_x', 'bucket_y')},
            },
        ),
    ]
