# configs/leads_fields.yaml
global:
  require_idempotency_header: true
  client_ts_max_skew_seconds: 7200  # 2h
  signed_token_required: true
  signing:
    drop_empty: true

form_kinds:
  email_ebook:
    fields:
      email: { required: false, max_length: 254, validators: ["email"] }
      first_name: { required: false, max_length: 100 }
      ebook_id: { required: false, max_length: 64 }
      newsletter_optin: { required: false, type: bool }
  contact_full:
    fields:
      first_name: { required: false, max_length: 100 }
      last_name: { required: false, max_length: 100 }
      email: { required: false, max_length: 254, validators: ["email"] }
      phone: { required: false, max_length: 32, validators: ["phone"] }
      address_line1: { required: false, max_length: 200 }
      address_line2: { required: false, max_length: 200 }
      city: { required: false, max_length: 100 }
      state: { required: false, max_length: 100 }
      postal_code: { required: false, max_length: 20, validators: ["postal"] }
      country: { required: false, max_length: 2 }
      message: { required: false, max_length: 2000 }
      preferred_channel: { required: false, max_length: 16 }
  checkout_intent:
    fields:
      course_slug: { required: true, max_length: 220 }
      currency: { required: true, max_length: 3 }
      coupon_code: { required: false, max_length: 64 }
      full_name: { required: false, max_length: 150 }
      first_name: { required: false, max_length: 100 }
      last_name: { required: false, max_length: 100 }
      email: { required: false, max_length: 254, validators: ["email"] }
      phone: { required: false, max_length: 32, validators: ["phone"] }
      billing_address_line1: { required: false, max_length: 200 }
      billing_address_line2: { required: false, max_length: 200 }
      billing_city: { required: false, max_length: 100 }
      billing_state: { required: false, max_length: 100 }
      billing_postal_code: { required: false, max_length: 20, validators: ["postal"] }
      billing_country: { required: false, max_length: 2 }
      company_name: { required: false, max_length: 150 }
      tax_id_type: { required: false, max_length: 16 }
      tax_id: { required: false, max_length: 32 }
      save_customer: { required: false, type: bool }
      accept_terms: { required: true, type: bool }
      invoice_language: { required: false, max_length: 8 }
  product_lead:
    fields:
      full_name: { required: true }
      phone: { required: true, min_digits: 6 }
      email: { required: false, validators: ["email"] }
      address: { required: false }

campaign_overrides: {}
