# configs/leads_fields.yaml
global:
  require_idempotency_header: true
  client_ts_max_skew_seconds: 7200  # 2h
  signed_token_required: false
  signing:
    drop_empty: true

# configs/leads_fields.yaml (extrait)
form_kinds:
  checkout_intent:
    fields:
      # course_slug: RETIRÉ
      pack_slug:         { required: true,  max_length: 64 }
      currency:          { required: true,  max_length: 3 }
      full_name:         { required: false, max_length: 150 }
      email:             { required: true,  max_length: 254, validators: ["email"] }
      phone:             { required: false, max_length: 32, validators: ["phone"] }
      address_line1:     { required: false, max_length: 200 }
      address_line2:     { required: false, max_length: 200 }
      city:              { required: false, max_length: 100 }
      state:             { required: false, max_length: 100 }
      postal_code:       { required: false, max_length: 20, validators: ["postal"] }
      country:           { required: false, max_length: 2 }
      coupon_code:       { required: false, max_length: 64 }
      payment_mode:      { required: false, max_length: 16 }    # ou payment_method selon ton mapping
      accept_terms:      { required: true,  type: bool }
      invoice_language:  { required: false, max_length: 8 }
