# configs/leads_fields.yaml
global:
  require_idempotency_header: true
  client_ts_max_skew_seconds: 7200
  signed_token_required: true

form_kinds:
  checkout_intent:
    fields:
      # identité / contact
      email: { required: false, max_length: 254, validators: ["email"] }
      phone: { required: true, max_length: 32, validators: ["phone"] }
      full_name: { required: false, max_length: 150 }
      first_name: { required: false, max_length: 100 }
      last_name: { required: false, max_length: 100 }

      # adresse (les vrais champs utilisés par le stepper)
      address_line1: { required: false, max_length: 200 }
      address_line2: { required: false, max_length: 200 }
      city: { required: false, max_length: 100 }
      state: { required: false, max_length: 100 }
      postal_code: { required: false, max_length: 20, validators: ["postal"] }
      country: { required: false, max_length: 2 }

      # paiement / panier
      currency: { required: false, max_length: 3 }
      payment_mode: { required: false, max_length: 16 }
      payment_method: { required: false, max_length: 16 }
      promotion_selected: { required: false, max_length: 64 }

      # packs / quantités / cross-sell
      pack_slug: { required: false, max_length: 64 }
      offer_key: { required: false, max_length: 64 }
      quantity: { required: false, max_length: 4 }
      bump_optin: { required: false, type: bool }
      context.complementary_slugs: { required: false, type: list }

      # légal
      accept_terms: { required: true, type: bool }
