# Generated by Django 5.2.4 on 2025-09-10 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'currency', 'country', 'active', 'effective_at', 'expires_at'], name='catalog_cou_course__a136af_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'currency', 'country', 'effective_at'), name='uniq_courseprice_keyslice')],
            },
        ),
    ]
