# Generated by Django 5.2.4 on 2025-09-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSidebarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='MAD', max_length=10)),
                ('promo_badge', models.CharField(blank=True, default='', max_length=100)),
                ('bundle_title', models.CharField(blank=True, default='', max_length=120)),
                ('cta_guest_label', models.CharField(blank=True, default='Acheter sans inscription', max_length=120)),
                ('cta_member_label', models.CharField(blank=True, default='Se connecter pour continuer', max_length=120)),
                ('cta_note', models.CharField(blank=True, default='', max_length=300)),
                ('price_override', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_pct_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_settings', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Réglages Sidebar (cours)',
            },
        ),
        migrations.CreateModel(
            name='CourseTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image_url', models.URLField(blank=True, default='')),
                ('hero_tag', models.CharField(blank=True, default='', max_length=120)),
                ('video_url', models.URLField(blank=True, default='')),
                ('video_label', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('enrollment_label', models.CharField(blank=True, default='', max_length=200)),
                ('rating_value', models.FloatField(default=0.0)),
                ('rating_percentage', models.PositiveSmallIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('description_title', models.CharField(blank=True, default='', max_length=120)),
                ('bundle_title', models.CharField(blank=True, default='', max_length=120)),
                ('curriculum_title', models.CharField(blank=True, default='', max_length=120)),
                ('instructors_title', models.CharField(blank=True, default='', max_length=120)),
                ('reviews_title', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_content', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Contenu Training (cours)',
            },
        ),
        migrations.CreateModel(
            name='SidebarBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=1)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.coursesidebarsettings')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SidebarInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=120)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_items', to='catalog.coursesidebarsettings')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.coursetrainingcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_sections', to='catalog.coursetrainingcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.trainingcurriculumsection')),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_blocks', to='catalog.coursetrainingcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('profile_url', models.URLField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='catalog.coursetrainingcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.TextField()),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.coursetrainingcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest CTA'), ('member', 'Member CTA')], max_length=12)),
                ('kind', models.CharField(choices=[('reverse', 'Reverse by name'), ('external', 'External URL')], default='reverse', max_length=12)),
                ('url_name', models.CharField(blank=True, default='', max_length=200)),
                ('url_kwargs', models.JSONField(blank=True, default=dict)),
                ('external_url', models.URLField(blank=True, default='')),
                ('append_next', models.BooleanField(default=False)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.coursesidebarsettings')),
            ],
            options={
                'unique_together': {('settings', 'role')},
            },
        ),
    ]
