# Generated by Django 5.2.4 on 2025-10-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_productbadge_productimage_testimonialmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('short_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('image_src', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'slug'),
            },
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('MAD', 'DHS Marocain')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProductCrossSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('label_override', models.CharField(blank=True, max_length=120)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complementary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to', to='catalog.complementaryproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sells', to='catalog.product')),
            ],
            options={
                'ordering': ('position', 'id'),
                'unique_together': {('product', 'complementary')},
            },
        ),
    ]
