# Generated by Django 5.2.4 on 2025-10-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_complementaryproduct_alter_courseprice_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('proofs', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, default='Voir plus de réalisations', max_length=120)),
                ('lightbox_enabled', models.BooleanField(default=True)),
                ('anchor_id', models.SlugField(blank=True, default='galerie', max_length=80)),
                ('product_code', models.CharField(blank=True, default='', help_text='Code produit/slug pour filtrer côté hydrateur', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('namespace', models.CharField(blank=True, default='core', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('badge', models.CharField(blank=True, default='Participante', max_length=60)),
                ('meta', models.CharField(blank=True, default='', max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.CharField(max_length=300)),
                ('webp', models.CharField(blank=True, max_length=300)),
                ('href', models.CharField(blank=True, max_length=300)),
                ('lang_code', models.CharField(blank=True, default='fr', max_length=10)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('product_code', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.gallery')),
            ],
            options={
                'verbose_name': 'Élément de galerie',
                'verbose_name_plural': 'Éléments de galerie',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['gallery', 'is_published'], name='catalog_gal_gallery_a7dcad_idx'), models.Index(fields=['product_code'], name='catalog_gal_product_b11ea9_idx')],
            },
        ),
    ]
