# Generated by Django 5.2.4 on 2025-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_gallery_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='subname',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
