# Generated by Django 5.2.4 on 2025-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_galleryitem_subname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='subname',
        ),
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
