# Generated by Django 5.2.4 on 2025-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_galleryitem_subname_product_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
