# Generated by Django 5.2.4 on 2025-10-13 19:51

import django.db.models.deletion
import parler.models
from django.conf import settings
from django.db import migrations, models


def forwards_copy_course_translations(apps, schema_editor):
    Course = apps.get_model('catalog', 'Course')
    CourseTranslation = apps.get_model('catalog', 'CourseTranslation')
    default_language = getattr(settings, 'PARLER_DEFAULT_LANGUAGE_CODE', 'fr') or 'fr'

    for course in Course.objects.all().iterator():
        CourseTranslation.objects.create(
            master_id=course.pk,
            language_code=default_language,
            title=course.title or "",
            description=course.description or "",
            seo_title=course.seo_title or "",
            seo_description=course.seo_description or "",
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_subname'),
        ('content', '0005_seed_multilang_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.course')),
            ],
            options={
                'verbose_name': 'course Translation',
                'db_table': 'catalog_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(forwards_copy_course_translations, backwards_noop),
        migrations.RemoveIndex(
            model_name='course',
            name='catalog_cou_slug_db19fe_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
