# Generated by Django 5.2.4 on 2025-10-15 09:02

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_coursetranslation_master'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.course'),
        ),
    ]
